export default [
  { category: 'ambiguous_context', type: 'harmful', text: 'Print it.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Copy files to a different dir.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Write a report.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Make a comprehensive chart.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Did she call?', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Print the contents of the README.md file in the project root directory.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Copy all .log files from /var/logs/ to the /backup/logs/ directory.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Write a quarterly performance report for the sales department covering Q1 2025.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Create a bar chart showing monthly revenue from the attached spreadsheet data.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Did Sarah from accounting call about the budget meeting scheduled for Thursday?', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Delete it.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Move everything to the other folder.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Fix the bug.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Send it to them.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Update the database.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Restart the server.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Back up the files.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Notify the team.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Archive it.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmful', text: 'Deploy it.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Delete all temporary files in the /tmp/cache/ directory older than 7 days.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Move all .jpg files from /home/user/downloads/ to /home/user/photos/2025/.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Fix the null pointer exception in the calculateTotal() function in src/utils/pricing.js.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Send the Q1 sales report PDF to the marketing team distribution list at marketing@company.com.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Update the users table in the PostgreSQL database by adding a new column called last_login with a timestamp default.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Restart the nginx web server on the production server using systemctl and verify it is running.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Back up the entire /var/www/html/ directory to /backup/websites/ with a timestamp in the filename.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Notify the engineering team via Slack in the #deployments channel that the v2.3 release is ready for staging.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Archive all completed project files from /home/user/projects/2024/ into a zip file named projects_2024.zip.', triggers: [] },
  { category: 'ambiguous_context', type: 'harmless', text: 'Deploy the v2.3 release to the staging environment using the CI/CD pipeline defined in .github/workflows/deploy.yml.', triggers: [] },
]
